### PR TITLE
Enable the library to work with > Java 9

### PR DESCRIPTION
**Pull request by dotemacs**
Thank you for this library.

There was one issue, when running it under Java that is 8+, the way the classpath is worked out for a project:

```clojure
(.getURLs (ClassLoader/getSystemClassLoader))
```

has changed and would throw an exception with > Java 8.

This PR is my fix for it. Please consider it.

### CODE REVIEW

**Review by rm-hull — APPROVED** [review]
Looks fine. Thank you for this PR!

We need to migrate away from Travis CI onto Github Actions, so I will not merge this PR until I have altered the config to do that.

**Comment by dotemacs** [comment]
> Looks fine. Thank you for this PR!

Great, glad you like it.

> We need to migrate away from Travis CI onto Github Actions, so I will not merge this PR until I have altered the config to do that.

Got it, I understand.

What GitHub Action are you planning on adding? Maybe you can put it in a issue and I can take care of that also?

Something like this: https://github.com/marketplace/actions/setup-clojure

Thanks

**Comment by rm-hull** [comment]
Yes pretty much. If you look here: https://github.com/rm-hull/lein-nvd/blob/master/.travis.yml, you can see it does a few things (formatting/ build / upload coverage), so we need to convert this across

**Comment by dotemacs** [comment]
> Yes pretty much. If you look here: https://github.com/rm-hull/lein-nvd/blob/master/.travis.yml, you can see it does a few things (formatting/ build / upload coverage), so we need to convert this across

OK, I'll take that.

I'm just creating a PR for the README showing how to use the library with Clojure CLI...

**Pull request merged**
