### PR TITLE
upgrade dependency-check-core to 3.3.1

### PR DESCRIPTION
**Pull request by minhtuannguyen**
upgrade dependency-check-core to 3.3.1

### CODE REVIEW

**Comment by rm-hull** [comment]
Hey @minhtuannguyen, thanks for the PR, but there are some tests failing - see the travis job: https://travis-ci.org/rm-hull/lein-nvd/builds/424341027

There is a specific test that asserts the expected dependency-check version number - indeed its probably worth having a sweep through the source code for `"3.2.1"`. You can run the tests with `lein test`, but they could take some time as it needs to download the data files.

Once everything goes green on travis, I'll push out a new version.

**Comment by minhtuannguyen** [comment]
ok I will take a look at the test.

**Comment by minhtuannguyen** [comment]
I fixed the test. Thank you for your fast response.

**Comment by rm-hull** [comment]
v0.5.4 released with your PR changes

**Pull request merged**
