### PR TITLE
Automated dependency management

### PR DESCRIPTION
**Pull request by dotemacs**
I've taken the liberty to implement automated dependency management.

Why?

The badge pointing to dependency versioning service, does not work.

But even if it did, wouldn't it be more convenient to have something
that let's you know that dependencies not up to date? And what more
convenient than an automated CI job that does just that?

I took the liberty of creating just that workflow. It does the
following:

- it checks for out of date dependencies
- if there are any, updates the badge
- but it also creates the PR with the updated dependencies

And since I've added deps.edn and the project uses Leiningen, I
thought that it would be convenient to automate the updating of both
deps.edn and project.clj with the outdated dependencies.

### CODE REVIEW

**Comment by dotemacs** [comment]
Some things to be aware of:

- scheduled workflows, like this one being added, only run if merged in `master`
- the line `workflow_dispatch:` means that you can set off the job manually, by clicking on it. You don't have to wait for the scheduled time.
- I picked the scheduled time for the job to be at 7:29AM UTC. Not sure how you feel about that, so maybe update it to some time that you think is more appropriate?
- The fact that the job is scheduled to run only once, means that the dependencies will be updated every 24 hours.

Let me know what you think, thanks

**Comment by rm-hull** [comment]
wow, so https://versions.deps.co/rm-hull/lein-nvd is not showing the latest deps?!?.. crap!

... in which case, yes this is most welcome

**Review by rm-hull — APPROVED** [review]
The PR thing is definitely good idea, but note that if the version of dependency-check changes then there is some extra manual work needed to make the tests go green

**Comment by dotemacs** [comment]
> The PR thing is definitely good idea, but note that if the version of dependency-check changes then there is some extra manual work needed to make the tests go green

Thanks for merging in the PR.

I agree that some attention will need to be paid to the workflow, to ensure that the dependencies for it are also kept up to date. Maybe a workflow that checks the dependencies of the workflow :) ? I'm joking here, but on the serious side, the libraries being used within the workflow will probably go out of date at some point. I think that the things we're using them for, we don't have to worry in the foreseeable future about them bit rotting. 

If you'd like you can fire off the `dependencies` workflow because it has `workflow_dispatch:`, which means that it can be run manually. Or you could wait until tomorrow 7:29 for it to kick off.

**Pull request merged**
